{% set name = "cheat" %}
{% set version = "2.2.3" %}
{% set sha256 = "d42df12cc42934a7e29c733d5938655ce7f4890af82b6facd8804d5932db542a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python

  run:
    - python
    - docopt >=0.6.1
    - pygments >=1.6.0

test:
  imports:
    - cheat
    - cheat.cheatsheets
    - cheat.test

about:
  home: https://github.com/chrisallenlane/cheat
  license: MIT/GPL3
  license_file: LICENSE
  summary: 'cheat allows you to create and view interactive cheatsheets on the command-line. It was designed to help remind *nix system administrators of options for commands that they use frequently, but not frequently enough to remember.'
  dev_url: https://github.com/chrisallenlane/cheat

extra:
  recipe-maintainers:
    - proinsias
