travis:
  secure:
    BINSTAR_TOKEN: SBaCnpAJZOWmzU3jAKkqN0exUir5LBCR7CT8VD8IVNexFzM7QPKXJTq2701mysKjobbTD0OCKMhp/FmuMjRBAIYBrkt9muo1ES0cP1059+j6swaSVxzLxTe/9kR9w4IuBfcF3OKvyuJrj7MXuAGNYmm0YwSbZLwNPwrhMzfL8g1jaESMJNzZvP+n0e06RlLonV+fI4ewPaQaARhBvoRLPYwpY29LP3L+t0uIi15hESvs2JeWiKtLnhmDdZIf535jf4z0QZISJ8XBl0KJ+KPLAojeZOS+vdqOxyoulCM+A21RPnp8TyNwF994EWow+zzZvtYXS4bbtvfx5p+LSpDWNHL6as9XLjLfkU16GQ2L7tGnYu0/EDa9U8yE5pJwuz2mraya+Kh4GuLc1M7xqiZny50miJEU25f2CL99xC6CMo9NjnYTs8ooJeRKtlxEFdJj+lXGeCAbXffZ3wLYpp7feBxsxSspUUJoDMFEJL3a42zbxFwtgPNlfRj0SNMkOv0sLor3JoYWEL0G09EFwC2+056rMf1UWiYe3T0AMw3UBW8iDmqRSIBD5VgEOH8j05Tjug18cZAj+52V6Tj3NkE/XtUx/0/YwtGYclJVqbsjX0J3gRvXZQ3+3a1Usz6HlulQ6DJaomQvIZBhHoaOPCivTh6XdOfPgWm7p4W6fla/FVM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
